apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-gate
  namespace: argocd
  labels:
    env: gate
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/finance-flow1/k8s-manifests.git
    targetRevision: HEAD
    path: environments/gate
  destination:
    server: https://kubernetes.default.svc
    namespace: gate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
