---
# Allows HTTPRoutes from finance-dev and finance-prod to attach to the finance-gateway
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-routes-to-gateway
  namespace: gate
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: finance-dev
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: finance-prod
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
