apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-prod
  namespace: argocd
  labels:
    env: prod
    app: postgres
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/finance-flow1/k8s-manifests.git
    targetRevision: HEAD
    path: charts/postgres
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: finance-prod
  syncPolicy:
    automated:
      prune: false    # Never auto-prune postgres to protect persistent data
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
