apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
  labels:
    env: dev
    app: rabbitmq
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/finance-flow1/k8s-manifests.git
    targetRevision: HEAD
    path: charts/rabbitmq
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: finance-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
