replicaCount: 1

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: "3-management-alpine"

service:
  amqp:
    port: 5672
  management:
    port: 15672

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Secret reference (pre-existing — NOT managed by Helm)
secrets:
  rabbitmq: rabbitmq-secret
